server:
  port: 8090
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: notegen6@gmail.com
    password: 01042005Nn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  application:
    name: security-security
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
token:
  sign:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
